config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'web/boards#show'

  scope module: :web do
    resource :board, only: :show
    resources :developers, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resource :password_recovery, only: [:new, :create, :show, :update]
  end

  namespace :admin do
    resources :users
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_password :password_recovery_token, validations: false

  has_many :my_tasks, class_name: 'Task',
                      inverse_of: :author,
                      foreign_key: :author_id,
                      dependent: :destroy
  has_many :assigned_tasks, class_name: 'Task',
                            inverse_of: :assignee,
                            foreign_key: :assignee_id,
                            dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }
  validates :email, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :email, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_url)
    else
      render(:new)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(admin_users_url)
    else
      render(:edit)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :type)
  end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < API::V1::ApplicationController
  def index
    users = User.all
      .ransack(ransack_params)
      .result
      .page(page)
      .per(per_page)

    respond_with(users, each_serializer: UserSerializer,
                        root: 'items',
                        meta: build_meta(users))
  end

  def show
    user = User.find(params[:id])

    respond_with(user, serializer: UserSerializer)
  end
end

app/views/admin/users/_form.html.slim
= simple_form_for @user, as: :user, url: url do |f|
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']
  p
    = f.button :submit, "Confirm", class: 'mdl-button--colored'
    = link_to "Back", admin_users_url, class: "mdl-button mdl-js-button mdl-button--raised"

app/views/admin/users/edit.html.slim
h4 Edit User

= render partial: "form", locals: { url: admin_user_path(@user) }

app/views/admin/users/index.html.slim
h3 Users List

.mdl-grid
  .mdl-cell.mdl-cell--2-col
    = link_to "Add New User", new_admin_user_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
  .mdl-cell.mdl-cell--7-col
  .mdl-cell.mdl-cell--3-col
    = search_form_for(@q, url: admin_users_url, method: :get) do |f|
      .mdl-textfield.mdl-js-textified.searchfield
        = f.search_field :email_cont, class: 'mdl-textfield__input'
        = f.label :email_cont, class: 'mdl-textfield__label' do
          i.material-icons search

.mdl-grid
  table.mdl-cell--12-col.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp
    thead
      tr
        th
          = sort_link(@q, :id, "#")
        th.mdl-data-table__cell--non-numeric
          = sort_link(@q, :first_name, "First Name")
        th.mdl-data-table__cell--non-numeric
          = sort_link(@q, :last_name, "Last Name")
        th.mdl-data-table__cell--non-numeric
          = sort_link(@q, :email, "Email")
        th.mdl-data-table__cell--non-numeric
          = sort_link(@q, :type, "Type")
        th.mdl-data-table__cell--non-numeric scope="col" Actions
    tbody
      - @users.each do |user|
        tr
          td= user.id
          td.mdl-data-table__cell--non-numeric
            = user.first_name
          td.mdl-data-table__cell--non-numeric
            = user.last_name
          td.mdl-data-table__cell--non-numeric
            = user.email
          td.mdl-data-table__cell--non-numeric
            = user.type
          td.mdl-data-table__cell--non-numeric
            => link_to "Edit", edit_admin_user_path(user)
            -if current_user.id != user.id
              =< link_to "Delete", admin_user_path(user), method: "delete", data: { confirm: "Are you sure?" }

.mdl-grid
  .mdl-cell.mdl-cell--8-col
    = paginate @users
  .mdl-cell.mdl-cell--4-col.mdl-typography--text-right
    = page_entries_info @users

app/views/admin/users/new.html.slim
h4 Create New User

= render partial: "form", locals: { url: admin_users_path }

app/views/admin/users/show.html.slim
h1 User Profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span Email:&nbsp
  strong= @user.email

= link_to "Back to Index", admin_users_path