config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'web/boards#show'

  scope module: :web do
    resource :board, only: :show
    resources :developers, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resource :password_recovery, only: [:new, :create, :show, :update]
  end

  namespace :admin do
    resources :users
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:index, :show]
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Task Manager"
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    - if !Rails.env.development?
      = stylesheet_packs_with_chunks_tag "application", media: "all"
    = javascript_packs_with_chunks_tag 'rollbar'

  body
    = javascript_packs_with_chunks_tag 'application'
    header.mdl-layout__header
      .mdl-layout__header-row
        label.mdl-button.mdl-js-button.mdl-button--icon
          i.material-icons tab
        span.mdl-layout-title
          = "Task Manager"
        .mdl-layout-spacer
        nav.mdl-navigation
          = link_to "Board", board_path, class: 'mdl-navigation__link'
          - if current_user
            - if current_user.is_a? Admin
              = link_to "Admin Page", admin_users_url, class: 'mdl-navigation__link'
            span.mdl-navigation__link
              = current_user.first_name
            = link_to "Log Out", session_path, method: "delete", data: { confirm: "Are you sure?" }, class: 'mdl-navigation__link'
          - else
            = link_to "Sign In", new_session_path, class: 'mdl-navigation__link'
            = link_to "Sign Up", new_developer_path, class: 'mdl-navigation__link'

    - flash.each do |name, msg|
      div class="mdl-snackbar mdl-snackbar--active flash flash-#{name}"
        div class="flash__text"
          = msg
        button class="flash__close" type="button" onclick="this.parentElement.hidden=true;"
          i.material-icons close


    main#main.mdl-layout__content
      .page-content
        = yield
    footer#footer.mdl-mini-footer
      .mdl-mini-footer__left-section
        .mdl-logo
          | &copy; Mike Kurkin @ Dualboot Learn 2022